#ifndef STM32F103_CONFIG_TEST_CONFIG_H_
#define STM32F103_CONFIG_TEST_CONFIG_H_

#include "stm32f10x.h"
#include "stm32f10x_gpio.h"

#define LIB_USE_LED 3
#define LIB_LED1_PINOUT {GPIOB, GPIO_Pin_12}
#define LIB_LED2_PINOUT {GPIOB, GPIO_Pin_13}
#define LIB_LED3_PINOUT {GPIOB, GPIO_Pin_14}

#define LIB_USE_BUTTON 2
#define LIB_BUTTON1_PINOUT {GPIOB, GPIO_Pin_6}
#define LIB_BUTTON2_PINOUT {GPIOB, GPIO_Pin_7}

#define LIB_USE_SPI 1
#define LIB_SPI1_SCK_PINOUT {GPIOA, GPIO_Pin_5}
#define LIB_SPI1_MISO_PINOUT {GPIOA, GPIO_Pin_6}
#define LIB_SPI1_MOSI_PINOUT {GPIOA, GPIO_Pin_7}
#define LIB_SPI1_SS_PINOUT {GPIOA, GPIO_Pin_4}
#define LIB_SPI1_DEPS {SPI1, RCC_APB2Periph_SPI1, LIB_SPI1_SCK_PINOUT, LIB_SPI1_MISO_PINOUT, LIB_SPI1_MOSI_PINOUT, LIB_SPI1_SS_PINOUT}

#endif  // STM32F103_CONFIG_TEST_CONFIG_H_
